### Numpy Operation

In [1]:
import numpy as np
abc=[1,2,3,4]
abc=np.array(abc)
abc

array([1, 2, 3, 4])

In [2]:
np.arange(0,20,3)#argument (Start,Stop,Step size)

array([ 0,  3,  6,  9, 12, 15, 18])

In [3]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [4]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [5]:
np.ones((4,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [6]:
np.linspace(0,100,10)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [7]:
np.linspace(0,100,15)

array([   0.        ,    7.14285714,   14.28571429,   21.42857143,
         28.57142857,   35.71428571,   42.85714286,   50.        ,
         57.14285714,   64.28571429,   71.42857143,   78.57142857,
         85.71428571,   92.85714286,  100.        ])

In [8]:
np.linspace(0,100,5)

array([   0.,   25.,   50.,   75.,  100.])

In [9]:
np.random.randint(0,100,(3,3))

array([[25, 96, 49],
       [95, 15, 60],
       [44, 90, 94]])

In [10]:
np.random.seed(42)
np.random.randint(0,100,(4,3))

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99]])

In [11]:
np.random.seed(42)
np.random.randint(0,100,(4,3))

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99]])

- In jupyter notebook to get same random number as result, seed setting in numpy required to be in same cell
- Outside cell it will not hold seed impact and we will get different result from numpy random function

In [12]:
np.random.randint(0,100,(4,3))

array([[23,  2, 21],
       [52,  1, 87],
       [29, 37,  1],
       [63, 59, 20]])

In [13]:
np.random.seed(42)
arr=np.random.randint(0,100,10)
arr

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [14]:
print('Maximum value from Array : {} & its location : {}').format(arr.max(),arr.argmax())
print('Minimum value from Array : {} & its location : {}').format(arr.max(),arr.argmin())
print('Average value from Array : {}').format(arr.mean())
print('Index of Sort order of array : {}').format(arr.argsort())
print('Sort order of array : {}').format(np.sort(arr))

Maximum value from Array : 92 & its location : 1
Minimum value from Array : 92 & its location : 2
Average value from Array : 62.4
Index of Sort order of array : [2 5 0 4 3 8 9 6 7 1]
Sort order of array : [14 20 51 60 71 74 74 82 86 92]


In [15]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
mat[3,7]

37

In [17]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [18]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [19]:
mat[0:4,3:6]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [20]:
mat[mat>49]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])