### Tensorflow Basic Syntax

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

/home/ubuntu/Spell_Correction/Spell_Corrections/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.5.0


In [2]:
hello=tf.constant('Hello')
print(type(hello))
print(hello)
world=tf.constant('World!')

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const:0", shape=(), dtype=string)


In [3]:
with tf.Session() as sess:
    result=sess.run(hello)+' '+sess.run(world)
print(result)

Hello World!


In [4]:
graph_one=tf.get_default_graph()
print(graph_one)

In [5]:
G2=tf.Graph()
print(G2)

In [6]:
with G2.as_default():
    print(G2 is tf.get_default_graph())

True


In [7]:
print(G2 is tf.get_default_graph())

False


In [8]:
G2.as_default()
print(G2 is tf.get_default_graph())

False


In [9]:
sess=tf.InteractiveSession()
tf_randu=tf.random_uniform((4,4))
print(tf_randu)
tf_var=tf.Variable(initial_value=tf_randu)
print(tf_var)

Tensor("random_uniform:0", shape=(4, 4), dtype=float32)
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


To Use initiatized variable required to initiate session as following

In [10]:
init=tf.global_variables_initializer()
sess.run(init)

In [11]:
sess.run(tf_var)

array([[0.8581815 , 0.5942013 , 0.9701412 , 0.76843476],
       [0.6822715 , 0.69343877, 0.40283144, 0.05375481],
       [0.9785193 , 0.5995555 , 0.30512023, 0.7259079 ],
       [0.6899127 , 0.52098525, 0.31069553, 0.19036126]], dtype=float32)

In [12]:
ph=tf.placeholder(tf.float32,shape=(None))

In [13]:
np.random.seed(101)
tf.set_random_seed(101)

In [14]:
rand_a=np.random.uniform(0,100,(5,5))
display(rand_a)
rand_b=np.random.uniform(0,100,(5,1))
display(rand_b)

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [15]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)
add_ab = a + b
mul_ab = a * b

In [16]:
with tf.Session() as sess:
    add_result=sess.run(add_ab,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    print('\n')
    mul_result=sess.run(mul_ab,feed_dict={a:rand_a,b:rand_b})
    print(mul_result)    

[[151.07166  156.49855  102.27921  116.58396  167.95949 ]
 [135.45622   82.76316  141.42784  124.22093   71.06043 ]
 [113.30171   93.09215   76.06819  136.43912  154.42728 ]
 [ 96.71727   81.83804  133.83675  146.38118  101.10579 ]
 [122.72681  105.982925  59.044632  67.9831    72.89292 ]]


[[5134.644   5674.25     283.12433 1705.4707  6813.8315 ]
 [4341.8125  1598.267   4652.734   3756.8293   988.94635]
 [3207.8113  2038.1029  1052.7742  4546.9805  5588.1157 ]
 [1707.379    614.02527 4434.989   5356.7773  2029.8555 ]
 [3714.0984  2806.6438   262.76764  747.19855 1013.292  ]]
